Update creation code generation
OffchainLabs/token-bridge-contracts pull request #58
Opened 2023-11-22 13:16 UTC by gvladika

2023-11-23 11:22 UTC, gzeoneth requested changes

2023-11-23 11:22 UTC, gzeoneth commented on contracts/tokenbridge/arbitrum/L2AtomicTokenBridgeFactory.sol
>      function _creationCodeFor(bytes memory code) internal pure returns (bytes memory) {
can we have this function as a lib function shared by both contracts?

2023-11-23 11:22 UTC, gzeoneth commented on contracts/tokenbridge/ethereum/L1AtomicTokenBridgeCreator.sol
>      function _creationCodeFor(bytes memory code) internal pure returns (bytes memory) {
This changes the returned address of 
https://github.com/OffchainLabs/token-bridge-contracts/blob/9907fa26bfdec30dbdf8585192ad4ae6103f97f2/contracts/tokenbridge/ethereum/L1AtomicTokenBridgeCreator.sol#L612-L618
we might want to have a way to redeploy the multicall contract even if the rest of the token bridge is already deployed using the old way

2023-12-06 10:39 UTC, gvladika commented
out of date

2023-12-06 10:39 UTC, closed without merging